INFO 10-20 22:02:47 [__init__.py:225] Automatically detected platform cuda.
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:49 [api_server.py:1886] vLLM API server version 0.1.dev10606+gf9e7ad540
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:49 [utils.py:243] non-default args: {'model': 'meta-llama/Meta-Llama-3-70B-Instruct', 'tensor_parallel_size': 2, 'data_parallel_size': 4}
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:50 [model.py:659] Resolved architecture: LlamaForCausalLM
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:50 [model.py:1746] Using max model len 8192
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:50 [scheduler.py:225] Chunked prefill is enabled with max_num_batched_tokens=8192.
[1;36m(APIServer pid=106171)[0;0m INFO 10-20 22:02:51 [utils.py:798] Started DP Coordinator process (PID: 106350)
INFO 10-20 22:02:54 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:02:54 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:02:54 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:02:54 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:02:54 [__init__.py:225] Automatically detected platform cuda.
[1;36m(EngineCore_DP3 pid=106356)[0;0m INFO 10-20 22:02:57 [core.py:730] Waiting for init message from front-end.
[1;36m(EngineCore_DP0 pid=106353)[0;0m INFO 10-20 22:02:57 [core.py:730] Waiting for init message from front-end.
[1;36m(EngineCore_DP2 pid=106355)[0;0m INFO 10-20 22:02:57 [core.py:730] Waiting for init message from front-end.
[1;36m(EngineCore_DP1 pid=106354)[0;0m INFO 10-20 22:02:58 [core.py:730] Waiting for init message from front-end.
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[1;36m(EngineCore_DP0 pid=106353)[0;0m INFO 10-20 22:02:58 [core.py:97] Initializing a V1 LLM engine (v0.1.dev10606+gf9e7ad540) with config: model='meta-llama/Meta-Llama-3-70B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-70B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Meta-Llama-3-70B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention', 'vllm::sparse_attn_indexer'], 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], 'cudagraph_copy_inputs': False, 'full_cuda_graph': True, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': 512, 'local_cache_dir': None}
[1;36m(EngineCore_DP0 pid=106353)[0;0m WARNING 10-20 22:02:58 [multiproc_executor.py:752] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_DP3 pid=106356)[0;0m INFO 10-20 22:02:58 [core.py:97] Initializing a V1 LLM engine (v0.1.dev10606+gf9e7ad540) with config: model='meta-llama/Meta-Llama-3-70B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-70B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Meta-Llama-3-70B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention', 'vllm::sparse_attn_indexer'], 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], 'cudagraph_copy_inputs': False, 'full_cuda_graph': True, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': 512, 'local_cache_dir': None}
[1;36m(EngineCore_DP3 pid=106356)[0;0m WARNING 10-20 22:02:58 [multiproc_executor.py:752] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_DP2 pid=106355)[0;0m INFO 10-20 22:02:58 [core.py:97] Initializing a V1 LLM engine (v0.1.dev10606+gf9e7ad540) with config: model='meta-llama/Meta-Llama-3-70B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-70B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Meta-Llama-3-70B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention', 'vllm::sparse_attn_indexer'], 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], 'cudagraph_copy_inputs': False, 'full_cuda_graph': True, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': 512, 'local_cache_dir': None}
[1;36m(EngineCore_DP2 pid=106355)[0;0m WARNING 10-20 22:02:58 [multiproc_executor.py:752] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_DP0 pid=106353)[0;0m INFO 10-20 22:02:58 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_3707c756'), local_subscribe_addr='ipc:///tmp/f64d779c-5c93-432e-8e3f-d6127a76033e', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_DP3 pid=106356)[0;0m INFO 10-20 22:02:58 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_e0d81263'), local_subscribe_addr='ipc:///tmp/de3f3f5f-c9c2-481a-87f8-00c9e8990d47', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_DP2 pid=106355)[0;0m INFO 10-20 22:02:58 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_b6d4b2f1'), local_subscribe_addr='ipc:///tmp/de72bf1e-0b91-4e0c-b4e3-553e11869034', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(EngineCore_DP1 pid=106354)[0;0m INFO 10-20 22:02:58 [core.py:97] Initializing a V1 LLM engine (v0.1.dev10606+gf9e7ad540) with config: model='meta-llama/Meta-Llama-3-70B-Instruct', speculative_config=None, tokenizer='meta-llama/Meta-Llama-3-70B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Meta-Llama-3-70B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention', 'vllm::sparse_attn_indexer'], 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], 'cudagraph_copy_inputs': False, 'full_cuda_graph': True, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': 512, 'local_cache_dir': None}
[1;36m(EngineCore_DP1 pid=106354)[0;0m WARNING 10-20 22:02:58 [multiproc_executor.py:752] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
[1;36m(EngineCore_DP1 pid=106354)[0;0m INFO 10-20 22:02:58 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_7a26e54d'), local_subscribe_addr='ipc:///tmp/2a4c07e6-6f02-48f5-919b-e0861db244dd', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:01 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:01 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:02 [__init__.py:225] Automatically detected platform cuda.
INFO 10-20 22:03:10 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_ea1abda4'), local_subscribe_addr='ipc:///tmp/17b0d784-b6f1-4f8f-b187-84bab82ecf82', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:10 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_d99a2764'), local_subscribe_addr='ipc:///tmp/6cd613d6-5a48-46b5-b793-3232c06a3e35', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:11 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_cf10f45f'), local_subscribe_addr='ipc:///tmp/22ba357f-33a9-4450-a487-9e46112dd735', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:11 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_b48aca1a'), local_subscribe_addr='ipc:///tmp/69fd678d-065d-4b3a-8cca-48eca4114536', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:11 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_c8d17bd7'), local_subscribe_addr='ipc:///tmp/25d26624-998a-43da-a51b-fae1e83ec37b', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:12 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_da0f4346'), local_subscribe_addr='ipc:///tmp/4c68cc32-1fee-4f20-ba6a-b11822432a11', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:12 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_7038a410'), local_subscribe_addr='ipc:///tmp/93b72eb2-bdd8-4c14-969c-5652642877b0', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:12 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 25165824, 10, 'psm_5de3cc55'), local_subscribe_addr='ipc:///tmp/9d7b90f7-75e7-477a-8e48-b02b82e31721', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=2 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=4 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=5 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=7 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=1 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=0 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=3 distributed_init_method=tcp://127.0.0.1:40825 for DP
INFO 10-20 22:03:12 [parallel_state.py:1160] Adjusting world_size=8 rank=6 distributed_init_method=tcp://127.0.0.1:40825 for DP
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
INFO 10-20 22:03:13 [pynccl.py:111] vLLM is using nccl==2.27.3
INFO 10-20 22:03:13 [pynccl.py:111] vLLM is using nccl==2.27.3
INFO 10-20 22:03:13 [pynccl.py:111] vLLM is using nccl==2.27.3
INFO 10-20 22:03:13 [pynccl.py:111] vLLM is using nccl==2.27.3
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [custom_all_reduce.py:37] Skipping P2P check and trusting the driver's P2P report.
INFO 10-20 22:03:15 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_5ceaf6d2'), local_subscribe_addr='ipc:///tmp/8939baa2-f3d7-4bbc-a363-f44220f96a9d', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:15 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_b8d00ed1'), local_subscribe_addr='ipc:///tmp/06604789-e36f-43a4-b386-5a9b1134e212', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:15 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_b5c69a5b'), local_subscribe_addr='ipc:///tmp/59ad3096-19f4-4fa8-ac26-00080f8c7cd1', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 10-20 22:03:15 [shm_broadcast.py:315] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_ef2da0df'), local_subscribe_addr='ipc:///tmp/ef188e70-da6f-4754-b9dd-d69729f4c740', remote_subscribe_addr=None, remote_addr_ipv6=False)
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 10-20 22:03:15 [pynccl.py:111] vLLM is using nccl==2.27.3
[Gloo] Rank 0 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 1 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 2 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
[Gloo] Rank 3 is connected to 3 peer ranks. Expected number of connected peer ranks is : 3
INFO 10-20 22:03:15 [pynccl.py:111] vLLM is using nccl==2.27.3
[Gloo] Rank 6 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 2 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 0 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 1 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 4 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 3 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 5 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
[Gloo] Rank 7 is connected to 7 peer ranks. Expected number of connected peer ranks is : 7
INFO 10-20 22:03:16 [pynccl.py:111] vLLM is using nccl==2.27.3
INFO 10-20 22:03:18 [cuda_communicator.py:122] Using AgRsAll2AllManager all2all manager.
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 0 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 1 in world size 8 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 7 in world size 8 is assigned as DP rank 3, PP rank 0, TP rank 1, EP rank 7
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 2 in world size 8 is assigned as DP rank 1, PP rank 0, TP rank 0, EP rank 2
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 6 in world size 8 is assigned as DP rank 3, PP rank 0, TP rank 0, EP rank 6
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 3 in world size 8 is assigned as DP rank 1, PP rank 0, TP rank 1, EP rank 3
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 5 in world size 8 is assigned as DP rank 2, PP rank 0, TP rank 1, EP rank 5
INFO 10-20 22:03:18 [parallel_state.py:1325] rank 4 in world size 8 is assigned as DP rank 2, PP rank 0, TP rank 0, EP rank 4
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:03:18 [gpu_model_runner.py:2860] Starting to load model meta-llama/Meta-Llama-3-70B-Instruct...
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:03:18 [cuda.py:403] Using Flash Attention backend on V1 engine.
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:03:19 [weight_utils.py:419] Using model weights format ['*.safetensors']
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:   0% Completed | 0/30 [00:00<?, ?it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:   3% Completed | 1/30 [00:00<00:24,  1.19it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:   7% Completed | 2/30 [00:01<00:22,  1.26it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  10% Completed | 3/30 [00:02<00:23,  1.16it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  13% Completed | 4/30 [00:03<00:22,  1.14it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  17% Completed | 5/30 [00:04<00:21,  1.19it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  20% Completed | 6/30 [00:05<00:20,  1.16it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  23% Completed | 7/30 [00:06<00:20,  1.13it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  27% Completed | 8/30 [00:06<00:19,  1.13it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  30% Completed | 9/30 [00:07<00:18,  1.11it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  33% Completed | 10/30 [00:08<00:18,  1.10it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  37% Completed | 11/30 [00:09<00:17,  1.10it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  40% Completed | 12/30 [00:10<00:14,  1.22it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  43% Completed | 13/30 [00:11<00:14,  1.18it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  47% Completed | 14/30 [00:12<00:13,  1.16it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  50% Completed | 15/30 [00:13<00:13,  1.12it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  53% Completed | 16/30 [00:14<00:12,  1.08it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  57% Completed | 17/30 [00:14<00:11,  1.11it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  60% Completed | 18/30 [00:15<00:11,  1.09it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  63% Completed | 19/30 [00:16<00:10,  1.07it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  67% Completed | 20/30 [00:17<00:09,  1.08it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  70% Completed | 21/30 [00:18<00:07,  1.13it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  73% Completed | 22/30 [00:19<00:07,  1.11it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  77% Completed | 23/30 [00:20<00:06,  1.09it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  80% Completed | 24/30 [00:21<00:05,  1.09it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  83% Completed | 25/30 [00:22<00:04,  1.08it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  87% Completed | 26/30 [00:23<00:03,  1.08it/s]
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:03:44 [default_loader.py:314] Loading weights took 24.80 seconds
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  90% Completed | 27/30 [00:24<00:02,  1.07it/s]
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:03:45 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 26.015472 seconds
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:03:45 [default_loader.py:314] Loading weights took 25.57 seconds
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:03:45 [default_loader.py:314] Loading weights took 24.77 seconds
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:03:45 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 26.649092 seconds
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  93% Completed | 28/30 [00:24<00:01,  1.13it/s]
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:03:46 [default_loader.py:314] Loading weights took 25.80 seconds
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:03:46 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 26.622837 seconds
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:03:46 [default_loader.py:314] Loading weights took 25.76 seconds
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:03:46 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 27.246197 seconds
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:03:46 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 27.303632 seconds
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:03:46 [default_loader.py:314] Loading weights took 25.86 seconds
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards:  97% Completed | 29/30 [00:25<00:00,  1.13it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards: 100% Completed | 30/30 [00:26<00:00,  1.45it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m Loading safetensors checkpoint shards: 100% Completed | 30/30 [00:26<00:00,  1.15it/s]
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m 
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:03:47 [default_loader.py:314] Loading weights took 26.12 seconds
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:03:47 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 27.946018 seconds
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:03:47 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 28.311268 seconds
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:03:47 [default_loader.py:314] Loading weights took 26.51 seconds
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:03:48 [gpu_model_runner.py:2921] Model loading took 65.7117 GiB and 28.908276 seconds
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_1_1/backbone for vLLM's torch.compile
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 10.86 s
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_0_0/backbone for vLLM's torch.compile
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 10.96 s
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_1_0/backbone for vLLM's torch.compile
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 10.91 s
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_0_1/backbone for vLLM's torch.compile
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 11.09 s
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_0_2/backbone for vLLM's torch.compile
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 11.09 s
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_1_2/backbone for vLLM's torch.compile
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 11.05 s
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:00 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_0_3/backbone for vLLM's torch.compile
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:00 [backends.py:623] Dynamo bytecode transform time: 11.16 s
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:01 [backends.py:609] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/99fcde7b48/rank_1_3/backbone for vLLM's torch.compile
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:01 [backends.py:623] Dynamo bytecode transform time: 11.22 s
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:03 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:04 [backends.py:248] Cache the graph for dynamic shape for later use
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:41 [backends.py:275] Compiling a graph for dynamic shape takes 40.22 s
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:41 [backends.py:275] Compiling a graph for dynamic shape takes 40.12 s
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:41 [backends.py:275] Compiling a graph for dynamic shape takes 40.39 s
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:41 [backends.py:275] Compiling a graph for dynamic shape takes 40.66 s
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:42 [backends.py:275] Compiling a graph for dynamic shape takes 40.70 s
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:42 [backends.py:275] Compiling a graph for dynamic shape takes 41.28 s
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:42 [backends.py:275] Compiling a graph for dynamic shape takes 41.31 s
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:42 [backends.py:275] Compiling a graph for dynamic shape takes 41.51 s
[1;36m(EngineCore_DP1 pid=106354)[0;0m INFO 10-20 22:04:46 [shm_broadcast.py:495] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).
[1;36m(EngineCore_DP3 pid=106356)[0;0m INFO 10-20 22:04:46 [shm_broadcast.py:495] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).
[1;36m(EngineCore_DP2 pid=106355)[0;0m INFO 10-20 22:04:47 [shm_broadcast.py:495] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).
[1;36m(EngineCore_DP0 pid=106353)[0;0m INFO 10-20 22:04:48 [shm_broadcast.py:495] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation).
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 51.62 s in total
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 51.62 s in total
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 52.37 s in total
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 51.07 s in total
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 51.48 s in total
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 52.55 s in total
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 51.35 s in total
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:53 [monitor.py:34] torch.compile takes 52.47 s in total
[1;36m(Worker_DP0_TP1 pid=107067)[0;0m INFO 10-20 22:04:54 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(Worker_DP0_TP0 pid=107063)[0;0m INFO 10-20 22:04:54 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793] EngineCore failed to start.
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793] Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 780, in run_engine_core
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 1075, in __init__
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 552, in __init__
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 113, in __init__
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 232, in _initialize_kv_caches
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     kv_cache_configs = get_kv_cache_configs(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]                        ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 1249, in get_kv_cache_configs
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     check_enough_kv_cache_memory(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 658, in check_enough_kv_cache_memory
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793]     raise ValueError(
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:54 [core.py:793] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
[1;36m(Worker_DP1_TP1 pid=107072)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(Worker_DP1_TP0 pid=107071)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(Worker_DP2_TP0 pid=107068)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(Worker_DP2_TP1 pid=107070)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793] EngineCore failed to start.
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793] Traceback (most recent call last):
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 780, in run_engine_core
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 1075, in __init__
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 552, in __init__
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 113, in __init__
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 232, in _initialize_kv_caches
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     kv_cache_configs = get_kv_cache_configs(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]                        ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 1249, in get_kv_cache_configs
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     check_enough_kv_cache_memory(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 658, in check_enough_kv_cache_memory
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793]     raise ValueError(
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:55 [core.py:793] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
[1;36m(Worker_DP3_TP1 pid=107069)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(Worker_DP3_TP0 pid=107066)[0;0m INFO 10-20 22:04:55 [gpu_worker.py:316] Available KV cache memory: -0.43 GiB
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793] EngineCore failed to start.
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793] Traceback (most recent call last):
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 780, in run_engine_core
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 1075, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 552, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 113, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 232, in _initialize_kv_caches
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     kv_cache_configs = get_kv_cache_configs(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]                        ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 1249, in get_kv_cache_configs
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     check_enough_kv_cache_memory(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 658, in check_enough_kv_cache_memory
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793]     raise ValueError(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:55 [core.py:793] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793] EngineCore failed to start.
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793] Traceback (most recent call last):
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 780, in run_engine_core
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 1075, in __init__
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 552, in __init__
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     super().__init__(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 113, in __init__
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 232, in _initialize_kv_caches
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     kv_cache_configs = get_kv_cache_configs(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]                        ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 1249, in get_kv_cache_configs
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     check_enough_kv_cache_memory(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 658, in check_enough_kv_cache_memory
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793]     raise ValueError(
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:56 [core.py:793] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
[1;36m(EngineCore_DP2 pid=106355)[0;0m ERROR 10-20 22:04:58 [multiproc_executor.py:163] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
[1;36m(EngineCore_DP0 pid=106353)[0;0m ERROR 10-20 22:04:58 [multiproc_executor.py:163] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
[1;36m(EngineCore_DP1 pid=106354)[0;0m ERROR 10-20 22:04:58 [multiproc_executor.py:163] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
[1;36m(EngineCore_DP3 pid=106356)[0;0m ERROR 10-20 22:04:58 [multiproc_executor.py:163] Worker proc VllmWorker-1 died unexpectedly, shutting down executor.
[1;36m(EngineCore_DP2 pid=106355)[0;0m Process EngineCore_DP2:
[1;36m(EngineCore_DP2 pid=106355)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_DP2 pid=106355)[0;0m     self.run()
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_DP2 pid=106355)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 797, in run_engine_core
[1;36m(EngineCore_DP2 pid=106355)[0;0m     raise e
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 780, in run_engine_core
[1;36m(EngineCore_DP2 pid=106355)[0;0m     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP2 pid=106355)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 1075, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m     super().__init__(
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 552, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m     super().__init__(
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 113, in __init__
[1;36m(EngineCore_DP2 pid=106355)[0;0m     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
[1;36m(EngineCore_DP2 pid=106355)[0;0m                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core.py", line 232, in _initialize_kv_caches
[1;36m(EngineCore_DP2 pid=106355)[0;0m     kv_cache_configs = get_kv_cache_configs(
[1;36m(EngineCore_DP2 pid=106355)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 1249, in get_kv_cache_configs
[1;36m(EngineCore_DP2 pid=106355)[0;0m     check_enough_kv_cache_memory(
[1;36m(EngineCore_DP2 pid=106355)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/core/kv_cache_utils.py", line 658, in check_enough_kv_cache_memory
[1;36m(EngineCore_DP2 pid=106355)[0;0m     raise ValueError(
[1;36m(EngineCore_DP2 pid=106355)[0;0m ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
[1;36m(APIServer pid=106171)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=106171)[0;0m   File "<frozen runpy>", line 198, in _run_module_as_main
[1;36m(APIServer pid=106171)[0;0m   File "<frozen runpy>", line 88, in _run_code
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/entrypoints/openai/api_server.py", line 1999, in <module>
[1;36m(APIServer pid=106171)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 96, in run
[1;36m(APIServer pid=106171)[0;0m     return __asyncio.run(
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/usr/local/lib/python3.12/asyncio/runners.py", line 195, in run
[1;36m(APIServer pid=106171)[0;0m     return runner.run(main)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=106171)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 48, in wrapper
[1;36m(APIServer pid=106171)[0;0m     return await main
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/entrypoints/openai/api_server.py", line 1930, in run_server
[1;36m(APIServer pid=106171)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/entrypoints/openai/api_server.py", line 1946, in run_server_worker
[1;36m(APIServer pid=106171)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=106171)[0;0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=106171)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/entrypoints/openai/api_server.py", line 191, in build_async_engine_client
[1;36m(APIServer pid=106171)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=106171)[0;0m                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=106171)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/entrypoints/openai/api_server.py", line 238, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=106171)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=106171)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/utils/func_utils.py", line 116, in inner
[1;36m(APIServer pid=106171)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/async_llm.py", line 219, in from_vllm_config
[1;36m(APIServer pid=106171)[0;0m     return cls(
[1;36m(APIServer pid=106171)[0;0m            ^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/async_llm.py", line 141, in __init__
[1;36m(APIServer pid=106171)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=106171)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core_client.py", line 120, in make_async_mp_client
[1;36m(APIServer pid=106171)[0;0m     return DPLBAsyncMPClient(*client_args)
[1;36m(APIServer pid=106171)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core_client.py", line 1176, in __init__
[1;36m(APIServer pid=106171)[0;0m     super().__init__(
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core_client.py", line 1016, in __init__
[1;36m(APIServer pid=106171)[0;0m     super().__init__(
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core_client.py", line 807, in __init__
[1;36m(APIServer pid=106171)[0;0m     super().__init__(
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/core_client.py", line 468, in __init__
[1;36m(APIServer pid=106171)[0;0m     with launch_core_engines(vllm_config, executor_class, log_stats) as (
[1;36m(APIServer pid=106171)[0;0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=106171)[0;0m   File "/usr/local/lib/python3.12/contextlib.py", line 144, in __exit__
[1;36m(APIServer pid=106171)[0;0m     next(self.gen)
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/utils.py", line 880, in launch_core_engines
[1;36m(APIServer pid=106171)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=106171)[0;0m   File "/home/ubuntu/pdd/vllm/vllm/v1/engine/utils.py", line 937, in wait_for_engine_startup
[1;36m(APIServer pid=106171)[0;0m     raise RuntimeError(
[1;36m(APIServer pid=106171)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
